name: leetcode_unofficial_api
description: "Unofficial LeetCode API: Level-up your coding practice with programmatic access to LeetCode data (problems, user stats, badges) & functionalities"
version: 0.0.1
repository: https://github.com/vijaykarthiktk/leetcode_unofficial_api
issue_tracker: https://github.com/vijaykarthiktk/leetcode_unofficial_api/issues
license: MIT

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
